server:
  port: 7777
spring :
   application :
      name : zipkinService  
   main:
    allow-bean-definition-overriding: true      
    
eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
      
management: 
  metrics:
    web:
      server:
        auto-time-requests: false